apiVersion: v1
kind: Pod
metadata:
  name: blip-pod
  namespace: dev
spec:
  containers:
    - name: blip-container
      image: gcr.io/blip-project-2026-tn/blip-app
      ports:
        - containerPort: 5000